## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  port: 5000
spring:
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: validate
        #hbm2ddl:
          #auto: create
    show-sql: true
  database:
    driverClassName: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring #jdbc:hsqldb:mem:spring
    username: root
    password:


