###for user
GET http://localhost:5000/api/user/dankar2

###get all users
GET http://localhost:5000/api/users

###get users page
GET http://localhost:5000/api/users/0

###add user
POST localhost:5000/api/createUser?adres_mail=dankar2@st.amu.edu.pl&name=Daniil&surname=Karunou&address_of_residence=Poznan

###delete user
DELETE http://localhost:5000/api/user/dankar2

###update user
PUT http://localhost:5000/api/user/edit


###for subject
###get subject by number
GET http://localhost:5000/api/subject/1

###get all subjects
GET http://localhost:5000/api/subjects

###get subjects page
GET http://localhost:5000/api/subjects/0

###create subject
POST localhost:5000/createSubject?user_login=dankar2&subject_name=Ak-47&category=gun&start_price=2700

###delete subject
DELETE http://localhost:5000/api/subject/1

###update subject
PUT http://localhost:5000/api/subject/edit

###for offer
###get offers from bidding
GET http://localhost:5000/api/offer/1

###add offer in this bidding
POST http://localhost:5000/api/addOffer/1

###for delivery option
###get delivery option by id
GET http://localhost:5000/api/deliveryOption/1

###get all delivery options
GET http://localhost:5000/api/deliveryOptions

###add delivery option
POST http://localhost:5000/api/addDeliveryOption

###delete delivery option
DELETE http://localhost:5000/api/deliveryOption/1

###update delivery option
PUT http://localhost:5000/api/deliveryOption/edit

###for bidding
###get bidding by id
GET http://localhost:5000/api/bidding/1

###get all biddings
GET http://localhost:5000/api/biddings

###get bidding page
GET http://localhost:5000/api/biddings/0

###delete bidding
DELETE http://localhost:5000/api/bidding/1

###update bidding
PUT http://localhost:5000/api/bidding/edit